//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="web-interface-submission", Namespace="gov/cms/pqrs/discharge/v1")]
[System.Xml.Serialization.XmlRootAttribute("web-interface-submission", Namespace="gov/cms/pqrs/discharge/v1", IsNullable=false)]
public partial class webinterfacesubmission {
    
    private string grouptinField;
    
    private patient[] patientField;

    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Key]
    public int Id { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("group-tin")]
    public string grouptin {
        get {
            return this.grouptinField;
        }
        set {
            this.grouptinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("patient")]
    public patient[] patient {
        get {
            return this.patientField;
        }
        set {
            this.patientField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="gov/cms/pqrs/discharge/v1")]
public partial class patient {

    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Key]
    public int Id { get; set; }

    private string medicareidField;
    
    private string patientfirstnameField;
    
    private string patientlastnameField;
    
    private string genderField;
    
    private string birthdateField;
    
    private string medicalrecordnumberField;
    
    private string otheridField;
    
    private string providernpiField;
    
    private string providernpitwoField;
    
    private string providernpithreeField;
    
    private string clinicidentifierField;
    
    private string generalcommentsField;
    
    private string medicalrecordfoundField;
    
    private string medicalnotqualifiedreasonField;
    
    private string medicalnotqualifieddateField;
    
    private string caremedconrankField;
    
    private string caremedconconfirmedField;
    
    private string dischargedateField;
    
    private string dischargeconfirmationField;
    
    private string officevisitField;
    
    private string medicationreconciliationField;
    
    private string caremedconcommentsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("medicare-id")]
    public string medicareid {
        get {
            return this.medicareidField;
        }
        set {
            this.medicareidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("patient-first-name")]
    public string patientfirstname {
        get {
            return this.patientfirstnameField;
        }
        set {
            this.patientfirstnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("patient-last-name")]
    public string patientlastname {
        get {
            return this.patientlastnameField;
        }
        set {
            this.patientlastnameField = value;
        }
    }
    
    /// <remarks/>
    public string gender {
        get {
            return this.genderField;
        }
        set {
            this.genderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("birth-date")]
    public string birthdate {
        get {
            return this.birthdateField;
        }
        set {
            this.birthdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("medical-record-number")]
    public string medicalrecordnumber {
        get {
            return this.medicalrecordnumberField;
        }
        set {
            this.medicalrecordnumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("other-id")]
    public string otherid {
        get {
            return this.otheridField;
        }
        set {
            this.otheridField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("provider-npi")]
    public string providernpi {
        get {
            return this.providernpiField;
        }
        set {
            this.providernpiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("provider-npi-two")]
    public string providernpitwo {
        get {
            return this.providernpitwoField;
        }
        set {
            this.providernpitwoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("provider-npi-three")]
    public string providernpithree {
        get {
            return this.providernpithreeField;
        }
        set {
            this.providernpithreeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("clinic-identifier")]
    public string clinicidentifier {
        get {
            return this.clinicidentifierField;
        }
        set {
            this.clinicidentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("general-comments")]
    public string generalcomments {
        get {
            return this.generalcommentsField;
        }
        set {
            this.generalcommentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("medical-record-found")]
    public string medicalrecordfound {
        get {
            return this.medicalrecordfoundField;
        }
        set {
            this.medicalrecordfoundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("medical-not-qualified-reason")]
    public string medicalnotqualifiedreason {
        get {
            return this.medicalnotqualifiedreasonField;
        }
        set {
            this.medicalnotqualifiedreasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("medical-not-qualified-date")]
    public string medicalnotqualifieddate {
        get {
            return this.medicalnotqualifieddateField;
        }
        set {
            this.medicalnotqualifieddateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("caremedcon-rank")]
    public string caremedconrank {
        get {
            return this.caremedconrankField;
        }
        set {
            this.caremedconrankField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("caremedcon-confirmed")]
    public string caremedconconfirmed {
        get {
            return this.caremedconconfirmedField;
        }
        set {
            this.caremedconconfirmedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("discharge-date")]
    public string dischargedate {
        get {
            return this.dischargedateField;
        }
        set {
            this.dischargedateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("discharge-confirmation")]
    public string dischargeconfirmation {
        get {
            return this.dischargeconfirmationField;
        }
        set {
            this.dischargeconfirmationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("office-visit")]
    public string officevisit {
        get {
            return this.officevisitField;
        }
        set {
            this.officevisitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("medication-reconciliation")]
    public string medicationreconciliation {
        get {
            return this.medicationreconciliationField;
        }
        set {
            this.medicationreconciliationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("caremedcon-comments")]
    public string caremedconcomments {
        get {
            return this.caremedconcommentsField;
        }
        set {
            this.caremedconcommentsField = value;
        }
    }
}
