//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 

namespace XMLSerializer.Provider
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "gov/cms/pqrs/provider/v1")]
    //[System.Xml.Serialization.XmlRootAttribute(Namespace = "gov/cms/pqrs/provider/v1", IsNullable = false)]
    [Table("export_provider")]
    public partial class export
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        [XmlIgnore]
        public int Id { get; set; }


        private fileauditdata fileauditdataField;

        private string exportperiodfromdateField;

        private string exportperiodtodateField;

        private webinterface webinterfaceField;

        private string typeField;

        private decimal versionField;

        public export()
        {
            this.typeField = "WEB-INTERFACE-PROVIDER";
            this.versionField = ((decimal)(3.0m));
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("file-audit-data")]
        public fileauditdata fileauditdata
        {
            get
            {
                return this.fileauditdataField;
            }
            set
            {
                this.fileauditdataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("export-period-from-date")]
        public string exportperiodfromdate
        {
            get
            {
                return this.exportperiodfromdateField;
            }
            set
            {
                this.exportperiodfromdateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("export-period-to-date")]
        public string exportperiodtodate
        {
            get
            {
                return this.exportperiodtodateField;
            }
            set
            {
                this.exportperiodtodateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("web-interface")]
        public webinterface webinterface
        {
            get
            {
                return this.webinterfaceField;
            }
            set
            {
                this.webinterfaceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "file-audit-data", Namespace = "gov/cms/pqrs/provider/v1")]
    [Table("fileauditdata_Provider")]
    public partial class fileauditdata
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        [XmlIgnore]
        public int Id { get; set; }


        private string filenumberField;

        private string createdateField;

        private string createtimeField;

        private string createbyField;

        private decimal versionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("file-number")]
        public string filenumber
        {
            get
            {
                return this.filenumberField;
            }
            set
            {
                this.filenumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("create-date")]
        public string createdate
        {
            get
            {
                return this.createdateField;
            }
            set
            {
                this.createdateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("create-time")]
        public string createtime
        {
            get
            {
                return this.createtimeField;
            }
            set
            {
                this.createtimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("create-by")]
        public string createby
        {
            get
            {
                return this.createbyField;
            }
            set
            {
                this.createbyField = value;
            }
        }

        /// <remarks/>
        public decimal version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "provider")]
    [Table("provider_Provider")]
    public partial class provider
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        [XmlIgnore]
        public int Id { get; set; }

        [XmlIgnore]
        private int batchId;
        public int BatchId
        {
            get
            {
                return (DateTime.UtcNow.Year - 1);
            }
            set { batchId = value; }
        }

        private string providernpiField;

        private string providerfirstnameField;

        private string providerlastnameField;

        private string providereinField;

        private string providercredentialsField;

        private string providerisoriginalField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("provider-npi")]
        public string providernpi
        {
            get
            {
                return this.providernpiField;
            }
            set
            {
                this.providernpiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("provider-first-name")]
        public string providerfirstname
        {
            get
            {
                return this.providerfirstnameField;
            }
            set
            {
                this.providerfirstnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("provider-last-name")]
        public string providerlastname
        {
            get
            {
                return this.providerlastnameField;
            }
            set
            {
                this.providerlastnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("provider-ein")]
        public string providerein
        {
            get
            {
                return this.providereinField;
            }
            set
            {
                this.providereinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("provider-credentials")]
        public string providercredentials
        {
            get
            {
                return this.providercredentialsField;
            }
            set
            {
                this.providercredentialsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("provider-is-original", DataType = "integer")]
        public string providerisoriginal
        {
            get
            {
                return this.providerisoriginalField;
            }
            set
            {
                this.providerisoriginalField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "web-interface-export")]
    [System.Xml.Serialization.XmlRootAttribute("web-interface-export", IsNullable = false)]
    [Table("webinterface_Provider")]
    public partial class webinterface
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        [XmlIgnore]
        public int Id { get; set; }

        [XmlIgnore]
        private int batchId;
        public int BatchId
        {
            get
            {
                return (DateTime.UtcNow.Year - 1);
            }
            set { batchId = value; }
        }

        private string grouptinField;

        private provider[] providerField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("group-tin")]
        public string grouptin
        {
            get
            {
                return this.grouptinField;
            }
            set
            {
                this.grouptinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("provider")]
        public provider[] provider
        {
            get
            {
                return this.providerField;
            }
            set
            {
                this.providerField = value;
            }
        }
    }
}