//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System;
// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


namespace XMLSerializer.Patient
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "web-interface-submission", Namespace = "gov/cms/pqrs/patient/v1")]
    [System.Xml.Serialization.XmlRootAttribute("web-interface-submission", Namespace = "gov/cms/pqrs/patient/v1", IsNullable = false)]
    [Table("webinterfacesubmission_Patient")]
    public partial class webinterfacesubmission
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        [XmlIgnore]
        public int Id { get; set; }

        [XmlIgnore]
        private int batchId;
        public int BatchId
        {
            get
            {
                return (DateTime.UtcNow.Year - 1);
            }
            set { batchId = value; }
        }

        private string grouptinField;

        private patient[] patientField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("group-tin")]
        public string grouptin
        {
            get
            {
                return this.grouptinField;
            }
            set
            {
                this.grouptinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("patient")]
        public patient[] patient
        {
            get
            {
                return this.patientField;
            }
            set
            {
                this.patientField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "gov/cms/pqrs/patient/v1")]
    [Table("patient_Patient")]
    public partial class patient
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        [XmlIgnore]
        public int Id { get; set; }

        [XmlIgnore]
        private int batchId;
        public int BatchId
        {
            get
            {
                return (DateTime.UtcNow.Year - 1);
            }
            set { batchId = value; }
        }

        private string medicareidField;

        private string patientfirstnameField;

        private string patientlastnameField;

        private string genderField;

        private string birthdateField;

        private string medicalrecordnumberField;

        private string otheridField;

        private string providernpiField;

        private string providernpitwoField;

        private string providernpithreeField;

        private string clinicidentifierField;

        private string generalcommentsField;

        private string medicalrecordfoundField;

        private string medicalnotqualifiedreasonField;

        private string medicalnotqualifieddateField;

        private string carefallsrankField;

        private string carefallsconfirmedField;

        private string fallsscreeningField;

        private string carefallscommentsField;

        private string cadrankField;

        private string cadconfirmedField;

        private string cadldlccontrolField;

        private string caddiabeteslvsdField;

        private string cadacearbField;

        private string cadcommentsField;

        private string dmrankField;

        private string dmconfirmedField;

        private string dmhba1ctestField;

        private string dmhba1cdateField;

        private string dmhba1cvalueField;

        private string dmcompositeexclusionField;

        private string dmrecentbpField;

        private string dmbpdateField;

        private string dmbpsystolicField;

        private string dmbpdiastolicField;

        private string dmldlctestField;

        private string dmldlcdateField;

        private string dmldlcvalueField;

        private string dmhba1ccompositetestField;

        private string dmhba1ccompositedateField;

        private string dmhba1ccompositevalueField;

        private string dmivdField;

        private string dmaspirinField;

        private string dmtobaccoField;

        private string dmcommentsField;

        private string hfrankField;

        private string hfconfirmedField;

        private string hflvsdField;

        private string hfbetablockerField;

        private string hfcommentsField;

        private string htnrankField;

        private string htnconfirmedField;

        private string htnrecentbpField;

        private string htnbpdateField;

        private string htnbpsystolicField;

        private string htnbpdiastolicField;

        private string htncommentsField;

        private string ivdrankField;

        private string ivdconfirmedField;

        private string ivdlipidperformedField;

        private string ivdlipiddateField;

        private string ivdldlcvalueField;

        private string ivdantithromboticField;

        private string ivdcommentsField;

        private string pcmammogramrankField;

        private string pcmammogramconfirmedField;

        private string pcmammogramField;

        private string pcmammogramcommentsField;

        private string pccolorectalrankField;

        private string pccolorectalconfirmedField;

        private string pccolorectalField;

        private string pccolorectalcommentsField;

        private string pcflushotrankField;

        private string pcflushotconfirmedField;

        private string pcflushotField;

        private string pcflushotcommentsField;

        private string pcpneumoshotrankField;

        private string pcpneumoshotconfirmedField;

        private string pcpneumoshotField;

        private string pcpneumoshotcommentsField;

        private string pcbmiscreenrankField;

        private string pcbmiscreenconfirmedField;

        private string pcbmicalculatedField;

        private string pcbminormalField;

        private string pcbmiplanField;

        private string pcbmicommentsField;

        private string pctobaccouserankField;

        private string pctobaccouseconfirmedField;

        private string pctobaccoscreenField;

        private string pctobaccocounselField;

        private string pctobaccousecommentsField;

        private string pcbloodpressurerankField;

        private string pcbloodpressureconfirmedField;

        private string pcbloodpressureField;

        private string pcbpnormalField;

        private string pcbpfollowupField;

        private string pcbpcommentsField;

        private string pcdepressionrankField;

        private string pcdepressionconfirmedField;

        private string pcdepressionField;

        private string pcdepressionpositiveField;

        private string pcdepressionplanField;

        private string pcdepressioncommentsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("medicare-id")]
        public string medicareid
        {
            get
            {
                return this.medicareidField;
            }
            set
            {
                this.medicareidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("patient-first-name")]
        public string patientfirstname
        {
            get
            {
                return this.patientfirstnameField;
            }
            set
            {
                this.patientfirstnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("patient-last-name")]
        public string patientlastname
        {
            get
            {
                return this.patientlastnameField;
            }
            set
            {
                this.patientlastnameField = value;
            }
        }

        /// <remarks/>
        public string gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("birth-date")]
        public string birthdate
        {
            get
            {
                return this.birthdateField;
            }
            set
            {
                this.birthdateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("medical-record-number")]
        public string medicalrecordnumber
        {
            get
            {
                return this.medicalrecordnumberField;
            }
            set
            {
                this.medicalrecordnumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("other-id")]
        public string otherid
        {
            get
            {
                return this.otheridField;
            }
            set
            {
                this.otheridField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("provider-npi")]
        public string providernpi
        {
            get
            {
                return this.providernpiField;
            }
            set
            {
                this.providernpiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("provider-npi-two")]
        public string providernpitwo
        {
            get
            {
                return this.providernpitwoField;
            }
            set
            {
                this.providernpitwoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("provider-npi-three")]
        public string providernpithree
        {
            get
            {
                return this.providernpithreeField;
            }
            set
            {
                this.providernpithreeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("clinic-identifier")]
        public string clinicidentifier
        {
            get
            {
                return this.clinicidentifierField;
            }
            set
            {
                this.clinicidentifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("general-comments")]
        public string generalcomments
        {
            get
            {
                return this.generalcommentsField;
            }
            set
            {
                this.generalcommentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("medical-record-found")]
        public string medicalrecordfound
        {
            get
            {
                return this.medicalrecordfoundField;
            }
            set
            {
                this.medicalrecordfoundField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("medical-not-qualified-reason")]
        public string medicalnotqualifiedreason
        {
            get
            {
                return this.medicalnotqualifiedreasonField;
            }
            set
            {
                this.medicalnotqualifiedreasonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("medical-not-qualified-date")]
        public string medicalnotqualifieddate
        {
            get
            {
                return this.medicalnotqualifieddateField;
            }
            set
            {
                this.medicalnotqualifieddateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("carefalls-rank")]
        public string carefallsrank
        {
            get
            {
                return this.carefallsrankField;
            }
            set
            {
                this.carefallsrankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("carefalls-confirmed")]
        public string carefallsconfirmed
        {
            get
            {
                return this.carefallsconfirmedField;
            }
            set
            {
                this.carefallsconfirmedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("falls-screening")]
        public string fallsscreening
        {
            get
            {
                return this.fallsscreeningField;
            }
            set
            {
                this.fallsscreeningField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("carefalls-comments")]
        public string carefallscomments
        {
            get
            {
                return this.carefallscommentsField;
            }
            set
            {
                this.carefallscommentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cad-rank")]
        public string cadrank
        {
            get
            {
                return this.cadrankField;
            }
            set
            {
                this.cadrankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cad-confirmed")]
        public string cadconfirmed
        {
            get
            {
                return this.cadconfirmedField;
            }
            set
            {
                this.cadconfirmedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cad-ldlc-control")]
        public string cadldlccontrol
        {
            get
            {
                return this.cadldlccontrolField;
            }
            set
            {
                this.cadldlccontrolField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cad-diabetes-lvsd")]
        public string caddiabeteslvsd
        {
            get
            {
                return this.caddiabeteslvsdField;
            }
            set
            {
                this.caddiabeteslvsdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cad-acearb")]
        public string cadacearb
        {
            get
            {
                return this.cadacearbField;
            }
            set
            {
                this.cadacearbField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cad-comments")]
        public string cadcomments
        {
            get
            {
                return this.cadcommentsField;
            }
            set
            {
                this.cadcommentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dm-rank")]
        public string dmrank
        {
            get
            {
                return this.dmrankField;
            }
            set
            {
                this.dmrankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dm-confirmed")]
        public string dmconfirmed
        {
            get
            {
                return this.dmconfirmedField;
            }
            set
            {
                this.dmconfirmedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dm-hba1c-test")]
        public string dmhba1ctest
        {
            get
            {
                return this.dmhba1ctestField;
            }
            set
            {
                this.dmhba1ctestField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dm-hba1c-date")]
        public string dmhba1cdate
        {
            get
            {
                return this.dmhba1cdateField;
            }
            set
            {
                this.dmhba1cdateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dm-hba1c-value")]
        public string dmhba1cvalue
        {
            get
            {
                return this.dmhba1cvalueField;
            }
            set
            {
                this.dmhba1cvalueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dm-composite-exclusion")]
        public string dmcompositeexclusion
        {
            get
            {
                return this.dmcompositeexclusionField;
            }
            set
            {
                this.dmcompositeexclusionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dm-recent-bp")]
        public string dmrecentbp
        {
            get
            {
                return this.dmrecentbpField;
            }
            set
            {
                this.dmrecentbpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dm-bp-date")]
        public string dmbpdate
        {
            get
            {
                return this.dmbpdateField;
            }
            set
            {
                this.dmbpdateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dm-bp-systolic")]
        public string dmbpsystolic
        {
            get
            {
                return this.dmbpsystolicField;
            }
            set
            {
                this.dmbpsystolicField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dm-bp-diastolic")]
        public string dmbpdiastolic
        {
            get
            {
                return this.dmbpdiastolicField;
            }
            set
            {
                this.dmbpdiastolicField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dm-ldlc-test")]
        public string dmldlctest
        {
            get
            {
                return this.dmldlctestField;
            }
            set
            {
                this.dmldlctestField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dm-ldlc-date")]
        public string dmldlcdate
        {
            get
            {
                return this.dmldlcdateField;
            }
            set
            {
                this.dmldlcdateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dm-ldlc-value")]
        public string dmldlcvalue
        {
            get
            {
                return this.dmldlcvalueField;
            }
            set
            {
                this.dmldlcvalueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dm-hba1c-composite-test")]
        public string dmhba1ccompositetest
        {
            get
            {
                return this.dmhba1ccompositetestField;
            }
            set
            {
                this.dmhba1ccompositetestField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dm-hba1c-composite-date")]
        public string dmhba1ccompositedate
        {
            get
            {
                return this.dmhba1ccompositedateField;
            }
            set
            {
                this.dmhba1ccompositedateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dm-hba1c-composite-value")]
        public string dmhba1ccompositevalue
        {
            get
            {
                return this.dmhba1ccompositevalueField;
            }
            set
            {
                this.dmhba1ccompositevalueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dm-ivd")]
        public string dmivd
        {
            get
            {
                return this.dmivdField;
            }
            set
            {
                this.dmivdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dm-aspirin")]
        public string dmaspirin
        {
            get
            {
                return this.dmaspirinField;
            }
            set
            {
                this.dmaspirinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dm-tobacco")]
        public string dmtobacco
        {
            get
            {
                return this.dmtobaccoField;
            }
            set
            {
                this.dmtobaccoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dm-comments")]
        public string dmcomments
        {
            get
            {
                return this.dmcommentsField;
            }
            set
            {
                this.dmcommentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("hf-rank")]
        public string hfrank
        {
            get
            {
                return this.hfrankField;
            }
            set
            {
                this.hfrankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("hf-confirmed")]
        public string hfconfirmed
        {
            get
            {
                return this.hfconfirmedField;
            }
            set
            {
                this.hfconfirmedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("hf-lvsd")]
        public string hflvsd
        {
            get
            {
                return this.hflvsdField;
            }
            set
            {
                this.hflvsdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("hf-beta-blocker")]
        public string hfbetablocker
        {
            get
            {
                return this.hfbetablockerField;
            }
            set
            {
                this.hfbetablockerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("hf-comments")]
        public string hfcomments
        {
            get
            {
                return this.hfcommentsField;
            }
            set
            {
                this.hfcommentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("htn-rank")]
        public string htnrank
        {
            get
            {
                return this.htnrankField;
            }
            set
            {
                this.htnrankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("htn-confirmed")]
        public string htnconfirmed
        {
            get
            {
                return this.htnconfirmedField;
            }
            set
            {
                this.htnconfirmedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("htn-recent-bp")]
        public string htnrecentbp
        {
            get
            {
                return this.htnrecentbpField;
            }
            set
            {
                this.htnrecentbpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("htn-bp-date")]
        public string htnbpdate
        {
            get
            {
                return this.htnbpdateField;
            }
            set
            {
                this.htnbpdateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("htn-bp-systolic")]
        public string htnbpsystolic
        {
            get
            {
                return this.htnbpsystolicField;
            }
            set
            {
                this.htnbpsystolicField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("htn-bp-diastolic")]
        public string htnbpdiastolic
        {
            get
            {
                return this.htnbpdiastolicField;
            }
            set
            {
                this.htnbpdiastolicField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("htn-comments")]
        public string htncomments
        {
            get
            {
                return this.htncommentsField;
            }
            set
            {
                this.htncommentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ivd-rank")]
        public string ivdrank
        {
            get
            {
                return this.ivdrankField;
            }
            set
            {
                this.ivdrankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ivd-confirmed")]
        public string ivdconfirmed
        {
            get
            {
                return this.ivdconfirmedField;
            }
            set
            {
                this.ivdconfirmedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ivd-lipid-performed")]
        public string ivdlipidperformed
        {
            get
            {
                return this.ivdlipidperformedField;
            }
            set
            {
                this.ivdlipidperformedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ivd-lipid-date")]
        public string ivdlipiddate
        {
            get
            {
                return this.ivdlipiddateField;
            }
            set
            {
                this.ivdlipiddateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ivd-ldlc-value")]
        public string ivdldlcvalue
        {
            get
            {
                return this.ivdldlcvalueField;
            }
            set
            {
                this.ivdldlcvalueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ivd-antithrombotic")]
        public string ivdantithrombotic
        {
            get
            {
                return this.ivdantithromboticField;
            }
            set
            {
                this.ivdantithromboticField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ivd-comments")]
        public string ivdcomments
        {
            get
            {
                return this.ivdcommentsField;
            }
            set
            {
                this.ivdcommentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pcmammogram-rank")]
        public string pcmammogramrank
        {
            get
            {
                return this.pcmammogramrankField;
            }
            set
            {
                this.pcmammogramrankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pcmammogram-confirmed")]
        public string pcmammogramconfirmed
        {
            get
            {
                return this.pcmammogramconfirmedField;
            }
            set
            {
                this.pcmammogramconfirmedField = value;
            }
        }

        /// <remarks/>
        public string pcmammogram
        {
            get
            {
                return this.pcmammogramField;
            }
            set
            {
                this.pcmammogramField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pcmammogram-comments")]
        public string pcmammogramcomments
        {
            get
            {
                return this.pcmammogramcommentsField;
            }
            set
            {
                this.pcmammogramcommentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pccolorectal-rank")]
        public string pccolorectalrank
        {
            get
            {
                return this.pccolorectalrankField;
            }
            set
            {
                this.pccolorectalrankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pccolorectal-confirmed")]
        public string pccolorectalconfirmed
        {
            get
            {
                return this.pccolorectalconfirmedField;
            }
            set
            {
                this.pccolorectalconfirmedField = value;
            }
        }

        /// <remarks/>
        public string pccolorectal
        {
            get
            {
                return this.pccolorectalField;
            }
            set
            {
                this.pccolorectalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pccolorectal-comments")]
        public string pccolorectalcomments
        {
            get
            {
                return this.pccolorectalcommentsField;
            }
            set
            {
                this.pccolorectalcommentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pcflushot-rank")]
        public string pcflushotrank
        {
            get
            {
                return this.pcflushotrankField;
            }
            set
            {
                this.pcflushotrankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pcflushot-confirmed")]
        public string pcflushotconfirmed
        {
            get
            {
                return this.pcflushotconfirmedField;
            }
            set
            {
                this.pcflushotconfirmedField = value;
            }
        }

        /// <remarks/>
        public string pcflushot
        {
            get
            {
                return this.pcflushotField;
            }
            set
            {
                this.pcflushotField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pcflushot-comments")]
        public string pcflushotcomments
        {
            get
            {
                return this.pcflushotcommentsField;
            }
            set
            {
                this.pcflushotcommentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pcpneumoshot-rank")]
        public string pcpneumoshotrank
        {
            get
            {
                return this.pcpneumoshotrankField;
            }
            set
            {
                this.pcpneumoshotrankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pcpneumoshot-confirmed")]
        public string pcpneumoshotconfirmed
        {
            get
            {
                return this.pcpneumoshotconfirmedField;
            }
            set
            {
                this.pcpneumoshotconfirmedField = value;
            }
        }

        /// <remarks/>
        public string pcpneumoshot
        {
            get
            {
                return this.pcpneumoshotField;
            }
            set
            {
                this.pcpneumoshotField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pcpneumoshot-comments")]
        public string pcpneumoshotcomments
        {
            get
            {
                return this.pcpneumoshotcommentsField;
            }
            set
            {
                this.pcpneumoshotcommentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pcbmiscreen-rank")]
        public string pcbmiscreenrank
        {
            get
            {
                return this.pcbmiscreenrankField;
            }
            set
            {
                this.pcbmiscreenrankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pcbmiscreen-confirmed")]
        public string pcbmiscreenconfirmed
        {
            get
            {
                return this.pcbmiscreenconfirmedField;
            }
            set
            {
                this.pcbmiscreenconfirmedField = value;
            }
        }

        /// <remarks/>
        public string pcbmicalculated
        {
            get
            {
                return this.pcbmicalculatedField;
            }
            set
            {
                this.pcbmicalculatedField = value;
            }
        }

        /// <remarks/>
        public string pcbminormal
        {
            get
            {
                return this.pcbminormalField;
            }
            set
            {
                this.pcbminormalField = value;
            }
        }

        /// <remarks/>
        public string pcbmiplan
        {
            get
            {
                return this.pcbmiplanField;
            }
            set
            {
                this.pcbmiplanField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pcbmi-comments")]
        public string pcbmicomments
        {
            get
            {
                return this.pcbmicommentsField;
            }
            set
            {
                this.pcbmicommentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pctobaccouse-rank")]
        public string pctobaccouserank
        {
            get
            {
                return this.pctobaccouserankField;
            }
            set
            {
                this.pctobaccouserankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pctobaccouse-confirmed")]
        public string pctobaccouseconfirmed
        {
            get
            {
                return this.pctobaccouseconfirmedField;
            }
            set
            {
                this.pctobaccouseconfirmedField = value;
            }
        }

        /// <remarks/>
        public string pctobaccoscreen
        {
            get
            {
                return this.pctobaccoscreenField;
            }
            set
            {
                this.pctobaccoscreenField = value;
            }
        }

        /// <remarks/>
        public string pctobaccocounsel
        {
            get
            {
                return this.pctobaccocounselField;
            }
            set
            {
                this.pctobaccocounselField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pctobaccouse-comments")]
        public string pctobaccousecomments
        {
            get
            {
                return this.pctobaccousecommentsField;
            }
            set
            {
                this.pctobaccousecommentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pcbloodpressure-rank")]
        public string pcbloodpressurerank
        {
            get
            {
                return this.pcbloodpressurerankField;
            }
            set
            {
                this.pcbloodpressurerankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pcbloodpressure-confirmed")]
        public string pcbloodpressureconfirmed
        {
            get
            {
                return this.pcbloodpressureconfirmedField;
            }
            set
            {
                this.pcbloodpressureconfirmedField = value;
            }
        }

        /// <remarks/>
        public string pcbloodpressure
        {
            get
            {
                return this.pcbloodpressureField;
            }
            set
            {
                this.pcbloodpressureField = value;
            }
        }

        /// <remarks/>
        public string pcbpnormal
        {
            get
            {
                return this.pcbpnormalField;
            }
            set
            {
                this.pcbpnormalField = value;
            }
        }

        /// <remarks/>
        public string pcbpfollowup
        {
            get
            {
                return this.pcbpfollowupField;
            }
            set
            {
                this.pcbpfollowupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pcbp-comments")]
        public string pcbpcomments
        {
            get
            {
                return this.pcbpcommentsField;
            }
            set
            {
                this.pcbpcommentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pcdepression-rank")]
        public string pcdepressionrank
        {
            get
            {
                return this.pcdepressionrankField;
            }
            set
            {
                this.pcdepressionrankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pcdepression-confirmed")]
        public string pcdepressionconfirmed
        {
            get
            {
                return this.pcdepressionconfirmedField;
            }
            set
            {
                this.pcdepressionconfirmedField = value;
            }
        }

        /// <remarks/>
        public string pcdepression
        {
            get
            {
                return this.pcdepressionField;
            }
            set
            {
                this.pcdepressionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pcdepression-positive")]
        public string pcdepressionpositive
        {
            get
            {
                return this.pcdepressionpositiveField;
            }
            set
            {
                this.pcdepressionpositiveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pcdepression-plan")]
        public string pcdepressionplan
        {
            get
            {
                return this.pcdepressionplanField;
            }
            set
            {
                this.pcdepressionplanField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pcdepression-comments")]
        public string pcdepressioncomments
        {
            get
            {
                return this.pcdepressioncommentsField;
            }
            set
            {
                this.pcdepressioncommentsField = value;
            }
        }
    }
}