//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 

namespace XMLSerializer.Ranking
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "web-interface-export", Namespace = "gov/cms/pqrs/patientranking/v1")]
    [System.Xml.Serialization.XmlRootAttribute("web-interface-export", Namespace = "gov/cms/pqrs/patientranking/v1", IsNullable = false)]
    [Table("webinterfaceexport_Ranking")]
    public partial class webinterfaceexport
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        [XmlIgnore]
        public int Id { get; set; }

        [XmlIgnore]
        private int batchId;
        public int BatchId
        {
            get
            {
                return (DateTime.UtcNow.Year - 1);
            }
            set { batchId = value; }
        }

        private string grouptinField;

        private patient[] patientField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("group-tin")]
        public string grouptin
        {
            get
            {
                return this.grouptinField;
            }
            set
            {
                this.grouptinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("patient")]
        public patient[] patient
        {
            get
            {
                return this.patientField;
            }
            set
            {
                this.patientField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "gov/cms/pqrs/patientranking/v1")]
    [Table("patient_Ranking")]
    public partial class patient
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        [XmlIgnore]
        public int Id { get; set; }

        [XmlIgnore]
        private int batchId;
        public int BatchId
        {
            get
            {
                return (DateTime.UtcNow.Year - 1);
            }
            set { batchId = value; }
        }

        private string medicareidField;

        private string patientfirstnameField;

        private string patientlastnameField;

        private string genderField;

        private string birthdateField;

        private string providernpiField;

        private string providerfirstnameField;

        private string providerlastnameField;

        private string providernpitwoField;

        private string providertwofirstnameField;

        private string providertwolastnameField;

        private string providernpithreeField;

        private string providerthreefirstnameField;

        private string providerthreelastnameField;

        private string clinicidentifierField;

        private string caremedconrankField;

        private string carefallsrankField;

        private string cadrankField;

        private string dmrankField;

        private string hfrankField;

        private string htnrankField;

        private string ivdrankField;

        private string pcmammogramrankField;

        private string pccolorectalrankField;

        private string pcflushotrankField;

        private string pcpneumoshotrankField;

        private string pcbmiscreenrankField;

        private string pctobaccouserankField;

        private string pcbloodpressurerankField;

        private string pcdepressionrankField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("medicare-id")]
        public string medicareid
        {
            get
            {
                return this.medicareidField;
            }
            set
            {
                this.medicareidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("patient-first-name")]
        public string patientfirstname
        {
            get
            {
                return this.patientfirstnameField;
            }
            set
            {
                this.patientfirstnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("patient-last-name")]
        public string patientlastname
        {
            get
            {
                return this.patientlastnameField;
            }
            set
            {
                this.patientlastnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("birth-date")]
        public string birthdate
        {
            get
            {
                return this.birthdateField;
            }
            set
            {
                this.birthdateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("provider-npi")]
        public string providernpi
        {
            get
            {
                return this.providernpiField;
            }
            set
            {
                this.providernpiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("provider-first-name")]
        public string providerfirstname
        {
            get
            {
                return this.providerfirstnameField;
            }
            set
            {
                this.providerfirstnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("provider-last-name")]
        public string providerlastname
        {
            get
            {
                return this.providerlastnameField;
            }
            set
            {
                this.providerlastnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("provider-npi-two")]
        public string providernpitwo
        {
            get
            {
                return this.providernpitwoField;
            }
            set
            {
                this.providernpitwoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("provider-two-first-name")]
        public string providertwofirstname
        {
            get
            {
                return this.providertwofirstnameField;
            }
            set
            {
                this.providertwofirstnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("provider-two-last-name")]
        public string providertwolastname
        {
            get
            {
                return this.providertwolastnameField;
            }
            set
            {
                this.providertwolastnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("provider-npi-three")]
        public string providernpithree
        {
            get
            {
                return this.providernpithreeField;
            }
            set
            {
                this.providernpithreeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("provider-three-first-name")]
        public string providerthreefirstname
        {
            get
            {
                return this.providerthreefirstnameField;
            }
            set
            {
                this.providerthreefirstnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("provider-three-last-name")]
        public string providerthreelastname
        {
            get
            {
                return this.providerthreelastnameField;
            }
            set
            {
                this.providerthreelastnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("clinic-identifier")]
        public string clinicidentifier
        {
            get
            {
                return this.clinicidentifierField;
            }
            set
            {
                this.clinicidentifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("caremedcon-rank")]
        public string caremedconrank
        {
            get
            {
                return this.caremedconrankField;
            }
            set
            {
                this.caremedconrankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("carefalls-rank")]
        public string carefallsrank
        {
            get
            {
                return this.carefallsrankField;
            }
            set
            {
                this.carefallsrankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cad-rank")]
        public string cadrank
        {
            get
            {
                return this.cadrankField;
            }
            set
            {
                this.cadrankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dm-rank")]
        public string dmrank
        {
            get
            {
                return this.dmrankField;
            }
            set
            {
                this.dmrankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("hf-rank")]
        public string hfrank
        {
            get
            {
                return this.hfrankField;
            }
            set
            {
                this.hfrankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("htn-rank")]
        public string htnrank
        {
            get
            {
                return this.htnrankField;
            }
            set
            {
                this.htnrankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ivd-rank")]
        public string ivdrank
        {
            get
            {
                return this.ivdrankField;
            }
            set
            {
                this.ivdrankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pcmammogram-rank")]
        public string pcmammogramrank
        {
            get
            {
                return this.pcmammogramrankField;
            }
            set
            {
                this.pcmammogramrankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pccolorectal-rank")]
        public string pccolorectalrank
        {
            get
            {
                return this.pccolorectalrankField;
            }
            set
            {
                this.pccolorectalrankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pcflushot-rank")]
        public string pcflushotrank
        {
            get
            {
                return this.pcflushotrankField;
            }
            set
            {
                this.pcflushotrankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pcpneumoshot-rank")]
        public string pcpneumoshotrank
        {
            get
            {
                return this.pcpneumoshotrankField;
            }
            set
            {
                this.pcpneumoshotrankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pcbmiscreen-rank")]
        public string pcbmiscreenrank
        {
            get
            {
                return this.pcbmiscreenrankField;
            }
            set
            {
                this.pcbmiscreenrankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pctobaccouse-rank")]
        public string pctobaccouserank
        {
            get
            {
                return this.pctobaccouserankField;
            }
            set
            {
                this.pctobaccouserankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pcbloodpressure-rank")]
        public string pcbloodpressurerank
        {
            get
            {
                return this.pcbloodpressurerankField;
            }
            set
            {
                this.pcbloodpressurerankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pcdepression-rank")]
        public string pcdepressionrank
        {
            get
            {
                return this.pcdepressionrankField;
            }
            set
            {
                this.pcdepressionrankField = value;
            }
        }
    }
}