//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System;
// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


namespace XMLSerializer.Clinic
{
    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace = "gov/cms/pqrs/clinic/v1")]
    //[System.Xml.Serialization.XmlRootAttribute(Namespace = "gov/cms/pqrs/clinic/v1", IsNullable = false)]
    //[Table("export_Clinic")]
    //public partial class export
    //{
    //    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    //    [Key]
    //    public int Id { get; set; }

    //    private fileauditdata fileauditdataField;

    //    private string exportperiodfromdateField;

    //    private string exportperiodtodateField;

    //    private webinterface webinterfaceField;

    //    private string typeField;

    //    private decimal versionField;

    //    public export()
    //    {
    //        this.typeField = "WEB-INTERFACE-CLINIC";
    //        this.versionField = ((decimal)(3.0m));
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute("file-audit-data")]
    //    public fileauditdata fileauditdata
    //    {
    //        get
    //        {
    //            return this.fileauditdataField;
    //        }
    //        set
    //        {
    //            this.fileauditdataField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute("export-period-from-date")]
    //    public string exportperiodfromdate
    //    {
    //        get
    //        {
    //            return this.exportperiodfromdateField;
    //        }
    //        set
    //        {
    //            this.exportperiodfromdateField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute("export-period-to-date")]
    //    public string exportperiodtodate
    //    {
    //        get
    //        {
    //            return this.exportperiodtodateField;
    //        }
    //        set
    //        {
    //            this.exportperiodtodateField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute("web-interface")]
    //    public webinterface webinterface
    //    {
    //        get
    //        {
    //            return this.webinterfaceField;
    //        }
    //        set
    //        {
    //            this.webinterfaceField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public string type
    //    {
    //        get
    //        {
    //            return this.typeField;
    //        }
    //        set
    //        {
    //            this.typeField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public decimal version
    //    {
    //        get
    //        {
    //            return this.versionField;
    //        }
    //        set
    //        {
    //            this.versionField = value;
    //        }
    //    }
    //}

    /// <remarks/>
   // [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
   // [System.SerializableAttribute()]
   // [System.Diagnostics.DebuggerStepThroughAttribute()]
   // [System.ComponentModel.DesignerCategoryAttribute("code")]
   // [System.Xml.Serialization.XmlTypeAttribute(TypeName = "file-audit-data", Namespace = "gov/cms/pqrs/clinic/v1")]
   //[Table("fileauditdata_Clinic")]
    //public partial class fileauditdata
    //{
    //    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    //    [Key]
    //    public int Id { get; set; }

    //    private string filenumberField;

    //    private string createdateField;

    //    private string createtimeField;

    //    private string createbyField;

    //    private decimal versionField;

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute("file-number")]
    //    public string filenumber
    //    {
    //        get
    //        {
    //            return this.filenumberField;
    //        }
    //        set
    //        {
    //            this.filenumberField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute("create-date")]
    //    public string createdate
    //    {
    //        get
    //        {
    //            return this.createdateField;
    //        }
    //        set
    //        {
    //            this.createdateField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute("create-time")]
    //    public string createtime
    //    {
    //        get
    //        {
    //            return this.createtimeField;
    //        }
    //        set
    //        {
    //            this.createtimeField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute("create-by")]
    //    public string createby
    //    {
    //        get
    //        {
    //            return this.createbyField;
    //        }
    //        set
    //        {
    //            this.createbyField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public decimal version
    //    {
    //        get
    //        {
    //            return this.versionField;
    //        }
    //        set
    //        {
    //            this.versionField = value;
    //        }
    //    }
    //}

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "clinic")]
    [Table("clinic_Clinic")]
    public partial class clinic
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        [XmlIgnore]
        public int Id { get; set; }

        [XmlIgnore]
        private int batchId;
        public int BatchId
        {
            get
            {
                return (DateTime.UtcNow.Year - 1);
            }
            set { batchId = value; }
        }

        private string clinicidentifierField;

        private string clinicnameField;

        private string clinicaddress1Field;

        private string clinicaddress2Field;

        private string cliniccityField;

        private string clinicstateField;

        private string cliniczipcodeField;

        private string clinicisoriginalField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("clinic-identifier")]
        public string clinicidentifier
        {
            get
            {
                return this.clinicidentifierField;
            }
            set
            {
                this.clinicidentifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("clinic-name")]
        public string clinicname
        {
            get
            {
                return this.clinicnameField;
            }
            set
            {
                this.clinicnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("clinic-address1")]
        public string clinicaddress1
        {
            get
            {
                return this.clinicaddress1Field;
            }
            set
            {
                this.clinicaddress1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("clinic-address2")]
        public string clinicaddress2
        {
            get
            {
                return this.clinicaddress2Field;
            }
            set
            {
                this.clinicaddress2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("clinic-city")]
        public string cliniccity
        {
            get
            {
                return this.cliniccityField;
            }
            set
            {
                this.cliniccityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("clinic-state")]
        public string clinicstate
        {
            get
            {
                return this.clinicstateField;
            }
            set
            {
                this.clinicstateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("clinic-zipcode")]
        public string cliniczipcode
        {
            get
            {
                return this.cliniczipcodeField;
            }
            set
            {
                this.cliniczipcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("clinic-is-original", DataType = "integer")]
        public string clinicisoriginal
        {
            get
            {
                return this.clinicisoriginalField;
            }
            set
            {
                this.clinicisoriginalField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "web-interface")]
    [System.Xml.Serialization.XmlRootAttribute("web-interface", IsNullable = false)]
    [Table("webinterface_clinic")]
    public partial class webinterface
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        [XmlIgnore]
        public int Id { get; set; }

        [XmlIgnore]
        private int batchId;
        public int BatchId
        {
            get
            {
                return (DateTime.UtcNow.Year - 1);
            }
            set { batchId = value; }
        }

     

        private string grouptinField;

        private clinic[] clinicField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("group-tin")]
        public string grouptin
        {
            get
            {
                return this.grouptinField;
            }
            set
            {
                this.grouptinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("clinic")]
        public clinic[] clinic
        {
            get
            {
                return this.clinicField;
            }
            set
            {
                this.clinicField = value;
            }
        }
    }
}